Control de análisis

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -48,3 +48,44 @@ jobs:
         with:
           name: sonar-report
           path: sonar-report.json
+
+      - name: Análisis del reporte
+        run: |
+          SONAR_REPORT=sonar-report.json
+
+          if [ ! -f "$SONAR_REPORT" ]; then
+            echo "No se encontró el reporte de SonarQube en la ruta especificada. Pipeline abortada."
+            exit 1
+          fi
+
+          if jq -e '.issues[] | select(.category == "VULNERABILITY")' "$SONAR_REPORT" > /dev/null; then
+            echo "Vulnerabilidades encontradas. Pipeline abortada."
+            exit 1
+          fi
+
+          if jq -e '.issues[] | select(.category == "BUG")' "$SONAR_REPORT" > /dev/null; then
+            echo "Bugs encontrados. Pipeline abortada."
+            exit 1
+          fi
+
+          if jq -e '.issues[] | select(.category == "CODE_SMELL")' "$SONAR_REPORT" > /dev/null; then
+            echo "Code smell encontrado. Pipeline abortada."
+            exit 1
+          fi
+
+          if jq -e '.issues[] | select(.rule == "duplicated_code")' "$SONAR_REPORT" > /dev/null; then
+            echo "Código duplicado. Pipeline abortada."
+            exit 1
+          fi
+
+          if jq -e '.metrics[] | select(.key == "coverage" and .value | tonumber < 80)' "$SONAR_REPORT" > /dev/null; then
+            echo "Baja cobertura de pruebas. Pipeline abortada."
+            exit 1
+          fi
+
+          if jq -e '.metrics[] | select(.category == "QUALITY_GATE" and .name == "Failed")' "$SONAR_REPORT" > /dev/null; then
+            echo "Quality Gate fallida. Pipeline abortada."
+            exit 1
+          fi
+
+          echo "El reporte de SonarQube está limpio. Continuando con el despliegue."
