Prueba simplificar pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,7 +52,10 @@ jobs:
 
       - name: Evaluate SonarQube Result
         run: |
-          echo "SonarQube step failed with outcome: ${{ steps.sonarqube.outcome }}"
+          if [ "${{ steps.sonarqube.outcome }}" != "success" ]; then
+            echo "SonarQube step failed with outcome: ${{ steps.sonarqube.outcome }}"
+            exit 1
+          fi
 
       # - name: Análisis del reporte
       #   run: |
